### ISSUE TITLE
ZombieFactory.sol

### ISSUE THREAD

**Issue by JoshuyPan** [loomnetwork/cryptozombies-lesson-code#48]
Hello there, 
Why inside the function on line 2:

` function _createZombie(string memory _name, uint _dna) private {

uint id = zombies.push(Zombie(_name, _dna)) - 1;
emit NewZombie(id, _name, _dna);
    }`

you associate zombie.push to an unsigned integer named ID. i tried to do the same on remix but i obviously had an error.
I am doing something wrong?

**Comment by elvisisvan** [comment]
which lesson? which chapter? have u tried asking chatgpt or bing ai?

**Comment by viraj-9901** [comment]
I guess this code snippet will not run on latest versions of solidity compiler, as there would be some warnings.
